version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5438:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
